modLoader="javafml"
loaderVersion="[38,)"
license="GPLv3"
issueTrackerURL="https://github.com/MeinKraft/Crimson-Slimes/issues"

[[mods]]
modId="crimsonslimes"
updateJSONURL = "https://github.com/MeinKraft/Crimson-Slimes/raw/1.18/update.json"
version="1.18-1.0.0"
displayName="Crimson Slimes"
authors="ยง4Crimson_Fluff"
logoFile="logo.png"
description=''' Slimey Slime Slimes '''
